apiVersion: v1
kind: Service
metadata:
  name: resize-service
  namespace: case
spec:
  type: LoadBalancer	
  selector:
    app: resize 
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 4000